---
title: "Fix NSW Transport Times"
author: "Davide Lorino"
date: "19/04/2019"
output: 
  html_document:
    theme: darkly
---

```{r, message = FALSE, warning = FALSE}
library(lubridate)
library(dplyr)
```
<br>
Here is a dummy dataset with those pesky times:

```{r}
nsw_transport_times <- data.frame("bizarro_times" = 
                                    c(hms("25:00:00", "00:00:00", "32:00:00", "19:00:00", "21:00:00")),
                                  "date" = c(dmy("22/10/1991"), dmy("23/10/1991"), dmy("24/10/1991"), dmy("25/10/1991"), dmy("26/10/1991")), 
                                  "trips" = c(1, 2, 3, 4, 5))

nsw_transport_times
```

Create the function to fix your time data:

```{r message = FALSE, warning = FALSE}
fix_nsw_transport_times <- function(nsw_transport_data, old_times, old_dates){
  new_nsw_transport_data <- nsw_transport_data %>%
    mutate(new_dates = 
             case_when(old_times == hms("00:00:00") ~ old_dates + days(1),
                       old_times > hms("24:00:00") ~ old_dates + days(1),
                       old_times <= hms("24:00:00") ~ old_dates)) %>%
    mutate(new_times =
             case_when(old_times == hms("00:00:00") ~ hms("00:00:00"),
                       old_times > hms("24:00:00") ~ hms(old_times) - hms("24:00:00"),
                       old_times <= hms("24:00:00") ~ old_times))
  new_nsw_transport_data
} 

```

Call your function:

```{r message = FALSE, warning = FALSE}

fixed_data <- fix_nsw_transport_times(nsw_transport_times, nsw_transport_times$bizarro_times, nsw_transport_times$date)

fixed_data
```


```{r}
library(dplyr)
fixed_data$new_seconds <- period_to_seconds(fixed_data$new_times)

fixed_data %>%
  arrange(new_dates, new_seconds)

```